apiVersion: apps/v1
kind: DaemonSets

metadata:

  name: ubuntu-ds 

  labels:

   app: ubuntu-ds

spec:

  selector:

    matchLabels:

      app: ubuntu-ds-pod

  template:

    metadata:

      labels:

        app: ubuntu-ds-pod

    spec:

      nodeSelector:

        label: ubuntu-ds-pod

      containers:

      - name: ubuntu

        image: ubuntu
